CREATE TABLE IF NOT EXISTS files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  original_name VARCHAR(255) NOT NULL,
  storage_path VARCHAR(1024) NOT NULL,
  file_type_id INT,
  entity_type VARCHAR(50) NOT NULL,
  entity_id INT NOT NULL,
  size INT NOT NULL,
  mime_type VARCHAR(255) NOT NULL,
  is_temporary TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (file_type_id) REFERENCES file_types(id) ON DELETE SET NULL
); 