CREATE TABLE IF NOT EXISTS food_beverage_details (
  hotel_id INT PRIMARY KEY,
  fnb_contact_position VARCHAR(255),
  fnb_contact_name VARCHAR(255),
  fnb_contact_phone VARCHAR(50),
  fnb_contact_email VARCHAR(255),
  restaurant_name VARCHAR(255),
  restaurant_cuisine VARCHAR(255),
  restaurant_seats INT,
  restaurant_opening_hours VARCHAR(255),
  restaurant_exclusive BOOLEAN DEFAULT FALSE,
  restaurant_price_minimum DECIMAL(10,2),
  bar_name VARCHAR(255),
  bar_seats INT,
  bar_exclusive BOOLEAN DEFAULT FALSE,
  bar_snacks_available BOOLEAN DEFAULT FALSE,
  bar_opening_hours VARCHAR(255),
  service_times VARCHAR(255),
  breakfast_restaurant_name VARCHAR(255),
  breakfast_start_time VARCHAR(50),
  breakfast_cost_per_person DECIMAL(10,2),
  breakfast_cost_per_child DECIMAL(10,2),
  breakfast_event_available BOOLEAN DEFAULT FALSE,
  operational_lead_time VARCHAR(255),
  allergy_diet_deadline VARCHAR(255),
  buffet_minimum_persons INT,
  fnb_packages_available BOOLEAN DEFAULT FALSE,
  extra_packages_customized BOOLEAN DEFAULT FALSE,
  coffee_break_items TEXT,
  lunch_standard_items TEXT,
  buffet_minimum_for_lunch INT,
  function_created_by VARCHAR(255),
  function_completion_time VARCHAR(255),
  function_required_depts VARCHAR(255),
  function_meeting_people VARCHAR(255),
  mice_desk_involvement VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_food_beverage_details_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE
); 